# src/OC/PlatformBundle/Resources/config/routing.yml

#oc_platform_home:
#    path:      /advert
#    defaults:  { _controller: OCPlatformBundle:Advert:index }
#    
#oc_platform_view:
#    path:      /advert/{id}
#    defaults:  { _controller: OCPlatformBundle:Advert:view }
#
#oc_platform_view_slug:
#    path:      /{year}/{slug}.{_format}
#    defaults:
#        _controller: OCPlatformBundle:Advert:viewSlug
#        format:      html
#    requirements:
#        year:   \d{4}
#        format: html|xml
#
#
#oc_platform_add:
#    path:      /add
#    defaults:  { _controller: OCPlatformBundle:Advert:add }
#    

#        voici l'exo sur la platform d echange


oc_platform_home:
    path:      /platform/{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*
        
oc_platform_view:
    path:      /platform/advert/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:view }
    requirements:
        id: \d+
    
oc_platform_add:
    path:      /platform/add
    defaults:  { _controller: OCPlatformBundle:Advert:add }

oc_platform_edit:
    path:      /platform/edit/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:edit }
    requirements:
        id: \d+

oc_platform_delete:
    path:      /platform/delete/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:delete }
    requirements:
        id: \d+
        
oc_platform_test:
    path:      /platform/test
    defaults:  { _controller: OCPlatformBundle:Advert:test }
    
oc_platform_purge:
    path:	/platform/purge/{days}
    defaults: { _contoller: OCPlatformBundle:Advert:purge}
    days:	15
    requirements:
        id: \d+