# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_home:
    path:      /advert
    defaults:  { _controller: OCPlatformBundle:Advert:index }
    
oc_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:view }

oc_platform_view_slug:
    path:      /{year}/{slug}.{_format}
    defaults:
        _controller: OCPlatformBundle:Advert:viewSlug
        format:      html
    requirements:
        year:   \d{4}
        format: html|xml


oc_platform_add:
    path:      /add
    defaults:  { _controller: OCPlatformBundle:Advert:add }