# src/OC/PlatformBundle/Ressources/config/services.yml

services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments: [@mailer, 50]
        # Tableau d'arguments @mailer : le service Mailer, %locale%: parametre locole pour récuperer la langue dans parameters.yml
        tags:
           - { name: twig.extension }
        calls:
           - [ setLocale, [ %locale% ] ]
           
    oc_platform.advert_purger:
        class: OC\PlatformBundle\Purger\OCPurger
        arguments: [@doctrine.orm.entity_manager]
        
    oc_platform.doctrine.notification:
        class: OC\PlatformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
     
    oc_platform.validator.antiflood:
    # Le nom du service
        class: OC\PlatformBundle\Validator\AntifloodValidator
        # La classe du service, ici notre validateur déjà créé
        arguments: [@request_stack, @doctrine.orm.entity_manager]
        # Les données qu'on injecte au service : la requête et l'EntityManager
        tags:
            - { name: validator.constraint_validator, alias: oc_platform_antiflood }
            # C'est avec l'alias qu'on retrouvera le service
            
    sdz_blog.ckeditor:
        class: OC\PlatformBundle\Form\Type\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }
            
    oc_platform.beta.html:
        class: OC\PlatformBundle\Beta\BetaHTML
        
    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments: [@oc_platform.beta.html, "2016-06-15"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }


#		Exemple pour l'écouteur d'événement Bigbrother
#    oc_platform.censorship_processor:
#        class:     AB\BigBrotherBundle\Bigbrother\CensorshipProcessor
#        arguments: [@mailer]
#
#    oc_platform.censorship_listener:
#        class:     AB\BigbrotherBundle\Bigbrother\CensorshipListener
#        arguments: [@oc_platform.censorship_processor, [1, 2, 3]]
#        tags:
#            - { name: kernel.event_listener, event: oc_platform.bigbrother.post_message, method: processMessage }