<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
	public function getApplicationsWithAdvert($limit) {
		
		$qb = $this->createQuerryBuilder('a');
		
		// On fait une jointure avec l'entité Advert avec pour alias « adv »
		$qb	->join('a.advert , adv')
			->addSelect('adv')
		;

		    // Puis on ne retourne que $limit résultats
		$qb->setMaxResults($limit);
		
		
		return $qb
				->getQuery()
				->getResult()
			;
	}

		public function isFlood($ip, $sec )
	{
		$qb = $this->createQueryBuilder('a')
			->select('COUNT(a)')
			->where('a.ip = :ip')
			->setParameter('ip', $ip)
			->andWhere('a.date >= :date')
			->setParameter('date', new \Datetime('-'.$sec.'seconds'));
		
		return (bool) $qb->getQuery()->getSingleScalarResult();
	}

}